config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, reset, \
    UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('resetpwd/', reset, name='reset'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='email')


    avatar = models.ImageField(upload_to='users/', verbose_name='avatar',
                               **NULLABLE)
    phone = models.CharField(max_length=150, verbose_name='phone', **NULLABLE)
    country = models.CharField(max_length=35, verbose_name='country',
                               **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from catalog.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name',
                  'phone', 'country', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from users.forms import UserRegisterForm, UserForm
from users.models import User


class LoginView(BaseLoginView):
    template_name = 'users/login.html'

class LogoutView(BaseLogoutView):
    pass

class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

    # FCV for email verification
    def form_valid(self, form):
        self.object = form.save()
        send_mail(
            subject='Верификация по почте',
            message=f'Это подтверждение регистрации пользователя {self.object.email}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.object.email]
        )
        return super().form_valid(form)


class UserUpdateView(UpdateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def reset(request):
    found = False  # flag to check existing user
    email = None
    user_to_save = None
    if request.method == 'POST':
        email = request.POST.get('email')
        users = User.objects.all()
        for user in users:
            if email == user.email:
                found = True
                user_to_save = user
                user
        # Generate new password
        if not found:
            print('No email found')
            render(request, 'users/reset.html')
        else:
            new_password = User.objects.make_random_password(length=12)
            # new_password = '123admin123'
            send_mail(
                subject='Восстановление пароля',
                message=(f'Пользователь - {email}\n'
                         f'Ваш новый пароль: {new_password}'),
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[email]
            )
            user_to_save.set_password(new_password)
            user_to_save.save()
            return redirect(reverse('users:login'))

    return render(request, 'users/reset.html')

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="row align-items-center justify-content-center" style="height: 50vh">
        <div class="col-4">
            <div class="card">
                <div class="card-header">Вход в профиль</div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <a href="{% url 'users:reset' %}" class="link-dark">Восстановить пароль?</a>
                        <br>
                        <button type="submit" class="btn btn-outline-primary mt-3">Вход
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="row align-items-center justify-content-center" style="height: 50vh">
        <div class="col-4">
            <div class="card">
                <div class="card-header">Регистрация пользователя</div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Регистрация
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/reset.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="row align-items-center justify-content-center"
         style="height: 50vh">
        <div class="col-4">
            <div class="card">
                <div class="card-header">Восстановление пароля</div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <label for="email" class="form-label">Почта</label>
                        <div class="input-group has-validation">
                            <span class="input-group-text bg-body-secondary">@</span>
                            <input type="email" class="form-control"
                                   name="email" placeholder="" required="">
                            <div class="invalid-feedback">
                                Введите почту.
                            </div>
                        </div>
                        <button
{#                                href="{% url 'users:gen_password' %}" #}
                                type="submit"
                                class="btn btn-outline-primary mt-3">
                            Восстановить
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">Мой профиль</div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Сохранить
                        </button>
                    </form>
                </div>
            </div>
        </div>

    </div>
{% endblock %}