catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import IndexView, contacts, BlogListView, BlogCreateView, \
    BlogDetailView, BlogUpdateView, BlogDeleteView, hidden_blog, \
    ProductCreateView, ProductUpdateView

app_name = CatalogConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('contacts/', contacts, name='contacts'),
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_view'),
    path('blog/edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
    path('blog/hidden/', hidden_blog, name="blog_hidden"),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, reset, \
    UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('resetpwd/', reset, name='reset'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
]

catalog/models.py
from django.conf import settings
from django.db import models


NULLABLE = {
    'null': True,
    'blank': True,
}

class Category(models.Model):
    name = models.CharField(max_length=250, verbose_name='Category')
    description = models.TextField(verbose_name='Description')
    # created_at = models.DateTimeField(**NULLABLE, verbose_name='Created At')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Product(models.Model):

    name = models.CharField(max_length=250, verbose_name='Name')
    description = models.TextField(**NULLABLE, verbose_name='Description')
    photo = models.ImageField(upload_to='shop/',**NULLABLE, verbose_name='Photo')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Category')
    price = models.IntegerField(verbose_name='Price')
    date_created = models.DateTimeField(auto_now_add=True, verbose_name='Date Created')
    date_modified = models.DateTimeField(**NULLABLE, verbose_name='Date Modified')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Owner')

    def __str__(self):
        return f'{self.name} (Price: {self.price}): {self.description}'

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'


class Contact(models.Model):
    name = models.CharField(max_length=250, verbose_name='Contact name')
    email = models.EmailField(max_length=250, verbose_name='Email')
    message = models.TextField(**NULLABLE, verbose_name='Message')

    def __str__(self):
        return f'{self.name} ({self.email}): {self.message}'

    class Meta:
        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Title')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)
    content = models.TextField(verbose_name='Content')
    preview = models.ImageField(upload_to='blog/',**NULLABLE, verbose_name='Preview')
    date_created = models.DateTimeField(verbose_name='Date Created')
    is_published = models.BooleanField(default=True, verbose_name='published')
    views_count = models.IntegerField(default=0, verbose_name='views')

    def __str__(self):
        return f"{self.title} ({self.date_created.date()}): {self.content}"

    class Meta:
        verbose_name = 'Blog'
        verbose_name_plural = 'Blogs'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Product')
    number = models.IntegerField(verbose_name='Version number')
    name = models.CharField(max_length=100, verbose_name='Version name')
    is_active = models.BooleanField(default=True, verbose_name='Active')

    def __str__(self):
        return f'Версия №{self.number}: {self.name}'

    class Meta:
        verbose_name = 'Version'
        verbose_name_plural = 'Versions'

catalog/forms.py
from django import forms

from catalog.models import Product


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'is_active':
                continue
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):

    restricted_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево',
                        'бесплатно', 'обман', 'полиция', 'радар']

    class Meta:
        model = Product
        exclude = ('date_modified', 'date_created')

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        if cleaned_data.lower() in self.restricted_words:
            raise forms.ValidationError('Данное название нельзя использовать')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        data_by_word = cleaned_data.lower().split()
        for word in data_by_word:
            if word in self.restricted_words:
                raise forms.ValidationError(
                    'Данное описание содержит запрещённые слова')
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'


class InlineVersionFormSet(forms.BaseInlineFormSet):
    def clean(self):
        super().clean()
        # counter to store number of active versions
        counter = 0
        # loop to check the number of active versions
        for form in self.forms:
            # check if version is active
            if form.cleaned_data.get('is_active'):
                counter += 1
            # raise error if more than one active version exist
            if counter > 1:
                print('Только одна активная версия продукта может быть. '
                      'Выберите одну версию продукта.')
                raise forms.ValidationError(
                    'Только одна активная версия продукта может быть. '
                    'Выберите одну версию продукта.')

catalog/views.py
from django.forms import inlineformset_factory, formset_factory
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, CreateView, ListView, \
    DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from catalog.forms import ProductForm, VersionForm, InlineVersionFormSet
from catalog.models import Product, Contact, Blog, Version


class IndexView(TemplateView):
    template_name = 'catalog/index.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Product.objects.all()
        context_data['version_list'] = Version.objects.all()
        return context_data

# def index(request):
#     # Convert QuerySet to List
#     # list_products = list(Product.objects.all())
#     # Print last five records
#     # if len(list_products) >= 5:
#     #     for product in list_products[-5:]:
#     #         print(product)
#     # else:
#     #     for product in list_products:
#     #         print(product)
#
#     # Get all products from catalog
#     products = Product.objects.all()
#
#     context = {
#         'object_list': products,
#     }
#
#     return render(request, 'catalog/index.html', context)

def contacts(request):
    data = Contact.objects.all()
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        print(f'{name} ({email}): {message}')
    return render(request, 'catalog/contacts.html',{"contacts": data})


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'date_created', 'preview', 'is_published')
    success_url = reverse_lazy('catalog:blog_list')

    def form_valid(self, form):
        if form.is_valid:
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', 'date_created', 'preview', 'is_published')

    def form_valid(self, form):
        if form.is_valid:
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:blog_view', args=[self.kwargs.get('pk')])


class BlogListView(ListView):
    model = Blog


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('catalog:blog_list')


def hidden_blog(request):
    context = {
        'object_list': Blog.objects.all(),
    }
    return render(request, 'catalog/blog_hidden.html', context)


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:index')

    # Identify owner of newly created product
    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('catalog:product_update', args=[self.object.pk])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormSet = inlineformset_factory(Product, Version,
                                                form=VersionForm,
                                                formset=InlineVersionFormSet,
                                                extra=1)
        if self.request.method == 'POST':
            formset = VersionFormSet(self.request.POST, instance=self.object)
        else:
            formset = VersionFormSet(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Base{% endblock title %}</title>
{#    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">#}
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        body {
            min-height: 100vh;
            min-height: -webkit-fill-available;
        }

        html {
            height: -webkit-fill-available;
        }

        main {
            height: 100vh;
            height: -webkit-fill-available;
            max-height: 100vh;
            overflow-x: auto;
            overflow-y: hidden;
        }

    </style>

</head>


<body>

<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="bootstrap" viewBox="0 0 118 94">
        <title>Bootstrap</title>
        <path fill-rule="evenodd" clip-rule="evenodd"
              d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
    </symbol>
    <symbol id="home" viewBox="0 0 16 16">
        <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z"/>
    </symbol>
    <symbol id="speedometer2" viewBox="0 0 16 16">
        <path d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z"/>
        <path fill-rule="evenodd"
              d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z"/>
    </symbol>
    <symbol id="table" viewBox="0 0 16 16">
        <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z"/>
    </symbol>
    <symbol id="people-circle" viewBox="0 0 16 16">
        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
        <path fill-rule="evenodd"
              d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
    </symbol>
    <symbol id="grid" viewBox="0 0 16 16">
        <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"/>
    </symbol>
    <symbol id="blog" viewBox="0 0 16 16">
        <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
        <path d="M3 5.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 8zm0 2.5a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5z"/>
    </symbol>
</svg>


<main class="d-flex flex-nowrap">

    <div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark"
         style="width: 280px;">
        <a href="/"
           class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
            <svg class="bi pe-none me-2" width="40" height="32">
                <use xlink:href="#bootstrap"/>
            </svg>
            <span class="fs-4">Меню</span>
        </a>
        <hr>
        <ul class="nav nav-pills flex-column mb-auto">
            <li class="nav-item">
                <!-- Create block for styling Main tab -->
                <a href="/" {% block tab_main %}
                   class="nav-link text-white" {% endblock tab_main %}>
                    <svg class="bi pe-none me-2" width="16" height="16">
                        <use xlink:href="#home"/>
                    </svg>
                    Главная
                </a>
            </li>
            <li>
                <a href="#" class="nav-link text-white">
                    <svg class="bi pe-none me-2" width="16" height="16">
                        <use xlink:href="#speedometer2"/>
                    </svg>
                    Категории
                </a>
            </li>
            <li>
                <a href="#" class="nav-link text-white">
                    <svg class="bi pe-none me-2" width="16" height="16">
                        <use xlink:href="#table"/>
                    </svg>
                    Заказы
                </a>
            </li>
            <li>
                <a href="/blog/" {% block tab_blogs %} class="nav-link text-white" {% endblock tab_blogs %}>
                    <svg class="bi pe-none me-2" width="16" height="16">
                        <use xlink:href="#blog"/>
                    </svg>
                    Блоги
                </a>
            </li>
            <li>
                <!-- Create block for styling Contacts tab -->
                <a href="/contacts/" {% block tab_contacts %}
                   class="nav-link text-white" {% endblock tab_contacts %}>
                    <svg class="bi pe-none me-2" width="16" height="16">
                        <use xlink:href="#people-circle"/>
                    </svg>
                    Контакты
                </a>
            </li>
        </ul>
        <hr>
        <div class="dropdown">
            <a href="#"
               class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
               data-bs-toggle="dropdown" aria-expanded="false">
                <img src="https://github.com/mdo.png" alt="" width="32"
                     height="32" class="rounded-circle me-2">
                <strong>Пользователь</strong>
            </a>
            <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                {% if user.is_authenticated %}
                    <li><a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выход</a></li>
                {% else %}
                    <li><a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{% url 'users:login' %}">Вход</a></li>
                {% endif %}
            </ul>
        </div>
    </div>


    <div class="d-flex flex-column p-3 bg-body-tertiary overflow-auto"
         style="height: 100vh;width: 100vw;">
        {% block content %} {% endblock content %}
    </div>
</main>

</body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Do you want to delete this blog "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-success">Confirm</button>
                        <a href="{% url 'catalog:blog_list' %}" class="btn btn-warning">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Save
                            {% else %}
                            Create
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/blog_hidden.html
{% extends 'catalog/base.html' %}
{% block title %} Lesson 20.1 blog {% endblock title %}
{% block tab_blogs %} class="nav-link active"
    aria-current="page" {% endblock tab_blogs %}
{% block content %}
    <h1 class="d-flex display-5 fw-normal justify-content-center align-items-end"
        style="height: 15vh;">Блоги</h1>
    <div class="row">
        <div class="col flex-lg-shrink-0 mb-5 mt-5">
            <a class="btn btn-outline-primary"
               href="{% url 'catalog:blog_create' %}">Добавить блог</a>
            <a class="btn btn-outline-secondary"
               href="#">Скрытые блоги</a>
        </div>
    </div>
    <div class="row">
        {% for object in object_list %}
            {% if not object.is_published %}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            {{ object.title }}
                        </div>
                        <div class="card-body">
                            <p class="card-text">
                                {{ object.date_created | date:"d M Y" }}
                            </p><br>
                            <p class="card-text">
                                {{ object.content | truncatechars:"40" }}
                            </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'catalog:blog_view' object.pk %}"
                                       type="button"
                                       class="btn btn-sm btn-outline-secondary">View</a>
                                    <a href='{% url 'catalog:blog_edit' object.pk %}'
                                       type="button"
                                       class="btn btn-sm btn-outline-secondary">Edit</a>
                                    <a href='{% url 'catalog:blog_delete' object.pk %}'
                                       type="button"
                                       class="btn btn-sm btn-outline-danger">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}
{% block title %} Lesson 20.1 blog {% endblock title %}
{% block tab_blogs %} class="nav-link active"
    aria-current="page" {% endblock tab_blogs %}
{% block content %}
    <h1 class="d-flex display-5 fw-normal justify-content-center align-items-end"
        style="height: 15vh;">Блоги</h1>
    <div class="row">
        <div class="col flex-lg-shrink-0 mb-5 mt-5">
            <a class="btn btn-outline-primary"
               href="{% url 'catalog:blog_create' %}">Добавить блог</a>
            <a class="btn btn-outline-secondary"
               href="{% url 'catalog:blog_hidden' %}">Скрытые блоги</a>
        </div>
    </div>
    <div class="row">
        {% for object in object_list %}
            {% if object.is_published %}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            {{ object.title }}
                        </div>
                        <div class="card-body">
                            <p class="card-text">
                                {{ object.date_created | date:"d M Y" }}
                            </p><br>
                            <p class="card-text">
                                {{ object.content | truncatechars:"40" }}
                            </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'catalog:blog_view' object.pk %}"
                                       type="button"
                                       class="btn btn-sm btn-outline-secondary">View</a>
                                    <a href='{% url 'catalog:blog_edit' object.pk %}'
                                       type="button"
                                       class="btn btn-sm btn-outline-secondary">Edit</a>
                                    <a href='{% url 'catalog:blog_delete' object.pk %}'
                                       type="button"
                                       class="btn btn-sm btn-outline-danger">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/index.html
{% extends "catalog/base.html" %}
{% block title %} Lesson 20.1 main {% endblock title %}
{% block tab_main %} class="nav-link active"
    aria-current="page" {% endblock tab_main %}
{% block content %}
    <h1 class="d-flex display-5 fw-normal justify-content-center align-items-end"
        style="height: 15vh;">Главная</h1>
    <p class="text-center fs-5 text-secondary">Вы находитесь на сайте,
        предназначеном для продажи товаров.</p>
    <div class="col-5 m-3">
        {% if user.is_authenticated %}
            <a href="{% url 'catalog:product_create' %}" class="btn btn-outline-primary"> Создать продукт </a>
        {% endif %}
    </div>
    <div class="row row-cols-lg-3 my-5 text-center align-items-center justify-content-center">

        {% for object in object_list %}
            {% include 'catalog/includes/inc_product.html' %}
        {% endfor %}

    </div>
{% endblock content %}